name = "txpipe/asteria"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'txpipe/asteria'"

[repository]
user = "txpipe"
project = "asteria"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
