[package]
name = "asteria-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
async-graphql = "7.0.3"
async-graphql-rocket = "7.0.3"