FROM rust:1.88 AS build

WORKDIR /app

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev cmake 

COPY ./Cargo.toml ./Cargo.toml
COPY ./backend ./backend

RUN cargo build --release

FROM rust:1.88-slim 
COPY --from=build /app/target/release/asteria-backend .
CMD ["./asteria-backend"]
